// frontend-vue/src/pages/ClienteForm.vue
<script setup lang="ts">
import { ref } from 'vue'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import CardHeader from '@/components/ui/CardHeader.vue'
import CardTitle from '@/components/ui/CardTitle.vue'
import CardDescription from '@/components/ui/CardDescription.vue'
import CardContent from '@/components/ui/CardContent.vue'
import CardFooter from '@/components/ui/CardFooter.vue'
import Input from '@/components/ui/Input.vue'
import { ApiError, createCliente, updateCliente, type Cliente, type Vendedor } from '@/lib/api'
import { formatCep, formatPhone } from '@/lib/format'
import { lookupCep } from '@/lib/viacep'

const props = defineProps<{
  cliente: Cliente | null
  vendedor: Vendedor[]
}>()

const emit = defineEmits<{
  saved: []
  cancel: []
}>()

const name = ref(props.cliente?.name ?? '')
const phone = ref(formatPhone(props.cliente?.phone ?? ''))
const email = ref(props.cliente?.email ?? '')
const street = ref(props.cliente?.street ?? '')
const number = ref(props.cliente?.number ?? '')
const city = ref(props.cliente?.city ?? '')
const state = ref(props.cliente?.state ?? '')
const zipCode = ref(formatCep(props.cliente?.zip_code ?? ''))
const location = ref(props.cliente?.location ?? '')
const vendedorId = ref(props.cliente?.vendedor_id ? String(props.cliente.vendedor_id) : '')

const isSubmitting = ref(false)
const error = ref<string | null>(null)
const fieldErrors = ref<Record<string, string[]>>({})
const isLookingUpCep = ref(false)
const cepError = ref<string | null>(null)

function handlePhoneInput(event: Event) {
  phone.value = formatPhone((event.target as HTMLInputElement).value)
}

function handleCepInput(event: Event) {
  zipCode.value = formatCep((event.target as HTMLInputElement).value)
}

async function handleCepBlur() {
  const digits = zipCode.value.replace(/\D/g, '')
  if (digits.length !== 8) return

  cepError.value = null
  isLookingUpCep.value = true
  try {
    const result = await lookupCep(digits)
    if (!result) {
      cepError.value = 'CEP não encontrado.'
      return
    }
    street.value = result.street
    city.value = result.city
    state.value = result.state
  } catch {
    cepError.value = 'Não foi possível consultar o CEP.'
  } finally {
    isLookingUpCep.value = false
  }
}

function handleClear() {
  name.value = ''
  phone.value = ''
  email.value = ''
  street.value = ''
  number.value = ''
  city.value = ''
  state.value = ''
  zipCode.value = ''
  location.value = ''
  vendedorId.value = ''
  error.value = null
  fieldErrors.value = {}
  cepError.value = null
}

async function handleSubmit() {
  error.value = null
  fieldErrors.value = {}

  if (!vendedorId.value) {
    error.value = 'Selecione um vendedor.'
    return
  }

  isSubmitting.value = true

  const data = {
    name: name.value,
    phone: phone.value,
    email: email.value,
    street: street.value,
    number: number.value,
    city: city.value,
    state: state.value,
    zip_code: zipCode.value,
    location: location.value,
    vendedor_id: Number(vendedorId.value),
  }

  try {
    if (props.cliente) {
      await updateCliente(props.cliente.id, data)
    } else {
      await createCliente(data)
    }
    emit('saved')
  } catch (err) {
    if (err instanceof ApiError) {
      error.value = err.message
      fieldErrors.value = err.errors ?? {}
    } else {
      error.value = 'Não foi possível conectar à API.'
    }
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>{{ cliente ? `Editar cliente: ${cliente.name}` : 'Cadastrar cliente' }}</CardTitle>
      <CardDescription v-if="cliente">ID: {{ cliente.id }}</CardDescription>
    </CardHeader>
    <form @submit.prevent="handleSubmit">
      <CardContent class="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <div class="flex flex-col gap-1 sm:col-span-2">
          <label for="name" class="flex items-center gap-2 border-l-4 border-destructive pl-2 text-sm font-medium">
            Nome <span class="text-destructive">*</span>
          </label>
          <Input id="name" v-model="name" required />
          <p v-for="msg in fieldErrors.name" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>

        <div class="flex flex-col gap-1">
          <label for="phone" class="flex items-center gap-2 border-l-4 border-destructive pl-2 text-sm font-medium">
            Telefone <span class="text-destructive">*</span>
          </label>
          <Input
            id="phone"
            v-model="phone"
            required
            placeholder="(XX) XXXXX-XXXX"
            maxlength="15"
            pattern="^\(\d{2}\) \d{5}-\d{4}$"
            title="Formato: (XX) XXXXX-XXXX"
            @input="handlePhoneInput"
          />
          <p v-for="msg in fieldErrors.phone" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>
        <div class="flex flex-col gap-1">
          <label for="email" class="text-sm font-medium">Email</label>
          <Input id="email" v-model="email" type="email" />
          <p v-for="msg in fieldErrors.email" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>

        <div class="flex flex-col gap-1">
          <label for="street" class="flex items-center gap-2 border-l-4 border-destructive pl-2 text-sm font-medium">
            Rua <span class="text-destructive">*</span>
          </label>
          <Input id="street" v-model="street" required />
          <p v-for="msg in fieldErrors.street" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>
        <div class="flex flex-col gap-1">
          <label for="number" class="flex items-center gap-2 border-l-4 border-destructive pl-2 text-sm font-medium">
            Número <span class="text-destructive">*</span>
          </label>
          <Input id="number" v-model="number" required />
          <p v-for="msg in fieldErrors.number" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>

        <div class="flex flex-col gap-1">
          <label for="city" class="flex items-center gap-2 border-l-4 border-destructive pl-2 text-sm font-medium">
            Cidade <span class="text-destructive">*</span>
          </label>
          <Input id="city" v-model="city" required />
          <p v-for="msg in fieldErrors.city" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>
        <div class="flex flex-col gap-1">
          <label for="state" class="flex items-center gap-2 border-l-4 border-destructive pl-2 text-sm font-medium">
            Estado <span class="text-destructive">*</span>
          </label>
          <Input id="state" v-model="state" required />
          <p v-for="msg in fieldErrors.state" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>

        <div class="flex flex-col gap-1">
          <label for="zip_code" class="flex items-center gap-2 border-l-4 border-destructive pl-2 text-sm font-medium">
            CEP <span class="text-destructive">*</span>
          </label>
          <Input
            id="zip_code"
            v-model="zipCode"
            required
            placeholder="00000-000"
            maxlength="9"
            pattern="^\d{5}-\d{3}$"
            title="Formato: 00000-000"
            @input="handleCepInput"
            @blur="handleCepBlur"
          />
          <p v-if="isLookingUpCep" class="text-xs text-muted-foreground">Buscando endereço...</p>
          <p v-if="cepError" class="text-xs text-destructive">{{ cepError }}</p>
          <p v-for="msg in fieldErrors.zip_code" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>
        <div class="flex flex-col gap-1">
          <label for="location" class="text-sm font-medium">Localização (Google Maps)</label>
          <Input
            id="location"
            v-model="location"
            placeholder="-23.550520, -46.633309"
            pattern="^-?\d{1,3}(\.\d+)?,\s*-?\d{1,3}(\.\d+)?$"
            title="Formato: latitude, longitude (ex: -23.550520, -46.633309)"
          />
          <p v-for="msg in fieldErrors.location" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        </div>

        <div class="flex flex-col gap-1">
          <label for="vendedor_id" class="text-sm font-medium">Vendedor</label>
          <select
            id="vendedor_id"
            v-model="vendedorId"
            class="h-8 rounded-lg border border-border bg-background px-2.5 text-sm"
          >
            <option value="">Selecione...</option>
            <option v-for="v in vendedor" :key="v.id" :value="String(v.id)">{{ v.nome }}</option>
          </select>
        </div>

        <p v-if="error" class="text-sm text-destructive sm:col-span-2">{{ error }}</p>
      </CardContent>
      <CardFooter class="gap-2">
        <Button type="submit" :disabled="isSubmitting">
          {{ isSubmitting ? 'Salvando...' : cliente ? 'Salvar alterações' : 'Cadastrar' }}
        </Button>
        <Button v-if="!cliente" type="button" variant="outline" @click="handleClear">Limpar formulário</Button>
        <Button type="button" variant="outline" @click="emit('cancel')">Cancelar</Button>
      </CardFooter>
    </form>
  </Card>
</template>

// frontend/src/pages/ClienteForm.tsx
import { useRef, useState, type FocusEvent, type FormEvent, type ReactNode } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { ApiError, createCliente, updateCliente, type Cliente, type Vendedor } from '@/lib/api'
import { formatCep, formatPhone } from '@/lib/format'
import { lookupCep } from '@/lib/viacep'

function RequiredLabel({ htmlFor, children }: { htmlFor: string; children: ReactNode }) {
  return (
    <label
      htmlFor={htmlFor}
      className="flex items-center gap-2 border-l-4 border-destructive pl-2 text-sm font-medium"
    >
      {children}
      <span className="text-destructive">*</span>
    </label>
  )
}

export function ClienteForm({
  cliente,
  vendedor,
  onSaved,
  onCancel,
}: {
  cliente: Cliente | null
  vendedor: Vendedor[]
  onSaved: () => void
  onCancel?: () => void
}) {
  const [formKey, setFormKey] = useState(0)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [fieldErrors, setFieldErrors] = useState<Record<string, string[]>>({})
  const [isLookingUpCep, setIsLookingUpCep] = useState(false)
  const [cepError, setCepError] = useState<string | null>(null)
  const streetRef = useRef<HTMLInputElement>(null)
  const cityRef = useRef<HTMLInputElement>(null)
  const stateRef = useRef<HTMLInputElement>(null)
  const [vendedorId, setVendedorId] = useState(cliente?.vendedor_id ? String(cliente.vendedor_id) : '')

  function handleClear() {
    setError(null)
    setFieldErrors({})
    setCepError(null)
    setFormKey((k) => k + 1)
  }

  async function handleCepBlur(event: FocusEvent<HTMLInputElement>) {
    const digits = event.target.value.replace(/\D/g, '')
    if (digits.length !== 8) return

    setCepError(null)
    setIsLookingUpCep(true)
    try {
      const result = await lookupCep(digits)
      if (!result) {
        setCepError('CEP não encontrado.')
        return
      }
      if (streetRef.current) streetRef.current.value = result.street
      if (cityRef.current) cityRef.current.value = result.city
      if (stateRef.current) stateRef.current.value = result.state
    } catch {
      setCepError('Não foi possível consultar o CEP.')
    } finally {
      setIsLookingUpCep(false)
    }
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError(null)
    setFieldErrors({})

    if (!vendedorId) {
      setError('Selecione um vendedor.')
      return
    }

    setIsSubmitting(true)

    const formData = new FormData(event.currentTarget)
    const data = {
      name: String(formData.get('name') ?? ''),
      phone: String(formData.get('phone') ?? ''),
      email: String(formData.get('email') ?? ''),
      street: String(formData.get('street') ?? ''),
      number: String(formData.get('number') ?? ''),
      city: String(formData.get('city') ?? ''),
      state: String(formData.get('state') ?? ''),
      zip_code: String(formData.get('zip_code') ?? ''),
      location: String(formData.get('location') ?? ''),
      vendedor_id: Number(vendedorId),
    }

    try {
      if (cliente) {
        await updateCliente(cliente.id, data)
      } else {
        await createCliente(data)
      }
      onSaved()
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message)
        setFieldErrors(err.errors ?? {})
      } else {
        setError('Não foi possível conectar à API.')
      }
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>{cliente ? `Editar cliente: ${cliente.name}` : 'Cadastrar cliente'}</CardTitle>
        {cliente && <CardDescription>ID: {cliente.id}</CardDescription>}
      </CardHeader>
      <form key={cliente ? `edit-${cliente.id}` : `new-${formKey}`} onSubmit={handleSubmit}>
        <CardContent className="grid grid-cols-2 gap-3">
          <div className="col-span-2 flex flex-col gap-1">
            <RequiredLabel htmlFor="name">Nome</RequiredLabel>
            <Input id="name" name="name" required defaultValue={cliente?.name} />
            {fieldErrors.name?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>

          <div className="flex flex-col gap-1">
            <RequiredLabel htmlFor="phone">Telefone</RequiredLabel>
            <Input
              id="phone"
              name="phone"
              required
              placeholder="(XX) XXXXX-XXXX"
              maxLength={15}
              pattern="^\(\d{2}\) \d{5}-\d{4}$"
              title="Formato: (XX) XXXXX-XXXX"
              defaultValue={formatPhone(cliente?.phone ?? '')}
              onChange={(e) => {
                e.target.value = formatPhone(e.target.value)
              }}
            />
            {fieldErrors.phone?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>
          <div className="flex flex-col gap-1">
            <label htmlFor="email" className="text-sm font-medium">
              Email
            </label>
            <Input id="email" name="email" type="email" defaultValue={cliente?.email ?? ''} />
            {fieldErrors.email?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>

          <div className="flex flex-col gap-1">
            <RequiredLabel htmlFor="street">Rua</RequiredLabel>
            <Input id="street" name="street" required ref={streetRef} defaultValue={cliente?.street} />
            {fieldErrors.street?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>
          <div className="flex flex-col gap-1">
            <RequiredLabel htmlFor="number">Número</RequiredLabel>
            <Input id="number" name="number" required defaultValue={cliente?.number ?? ''} />
            {fieldErrors.number?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>

          <div className="flex flex-col gap-1">
            <RequiredLabel htmlFor="city">Cidade</RequiredLabel>
            <Input id="city" name="city" required ref={cityRef} defaultValue={cliente?.city} />
            {fieldErrors.city?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>
          <div className="flex flex-col gap-1">
            <RequiredLabel htmlFor="state">Estado</RequiredLabel>
            <Input id="state" name="state" required ref={stateRef} defaultValue={cliente?.state} />
            {fieldErrors.state?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>

          <div className="flex flex-col gap-1">
            <RequiredLabel htmlFor="zip_code">CEP</RequiredLabel>
            <Input
              id="zip_code"
              name="zip_code"
              required
              placeholder="00000-000"
              maxLength={9}
              pattern="^\d{5}-\d{3}$"
              title="Formato: 00000-000"
              defaultValue={formatCep(cliente?.zip_code ?? '')}
              onChange={(e) => {
                e.target.value = formatCep(e.target.value)
              }}
              onBlur={handleCepBlur}
            />
            {isLookingUpCep && <p className="text-xs text-muted-foreground">Buscando endereço...</p>}
            {cepError && <p className="text-xs text-destructive">{cepError}</p>}
            {fieldErrors.zip_code?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>
          <div className="flex flex-col gap-1">
            <label htmlFor="location" className="text-sm font-medium">
              Localização (Google Maps)
            </label>
            <Input
              id="location"
              name="location"
              placeholder="-23.550520, -46.633309"
              pattern="^-?\d{1,3}(\.\d+)?,\s*-?\d{1,3}(\.\d+)?$"
              title="Formato: latitude, longitude (ex: -23.550520, -46.633309)"
              defaultValue={cliente?.location ?? ''}
            />
            {fieldErrors.location?.map((msg) => (
              <p key={msg} className="text-xs text-destructive">
                {msg}
              </p>
            ))}
          </div>

          <div className="flex flex-col gap-1">
            <label htmlFor="vendedor_id" className="text-sm font-medium">
              Vendedor
            </label>
            <select
              id="vendedor_id"
              className="h-8 rounded-lg border border-border bg-background px-2.5 text-sm"
              value={vendedorId}
              onChange={(e) => setVendedorId(e.target.value)}
            >
              <option value="">Selecione...</option>
              {vendedor.map((vendedor) => (
                <option key={vendedor.id} value={vendedor.id}>
                  {vendedor.nome}
                </option>
              ))}
            </select>
          </div>

          {error && <p className="col-span-2 text-sm text-destructive">{error}</p>}
        </CardContent>
        <CardFooter className="gap-2">
          <Button type="submit" disabled={isSubmitting}>
            {isSubmitting ? 'Salvando...' : cliente ? 'Salvar alterações' : 'Cadastrar'}
          </Button>
          {!cliente && (
            <Button type="button" variant="outline" onClick={handleClear}>
              Limpar formulário
            </Button>
          )}
          {onCancel && (
            <Button type="button" variant="outline" onClick={onCancel}>
              Cancelar
            </Button>
          )}
        </CardFooter>
      </form>
    </Card>
  )
}
