// frontend-vue/src/pages/VendedorForm.vue
<script setup lang="ts">
import { ref } from 'vue'
import Button from '@/components/ui/Button.vue'
import Card from '@/components/ui/Card.vue'
import CardHeader from '@/components/ui/CardHeader.vue'
import CardTitle from '@/components/ui/CardTitle.vue'
import CardDescription from '@/components/ui/CardDescription.vue'
import CardContent from '@/components/ui/CardContent.vue'
import CardFooter from '@/components/ui/CardFooter.vue'
import Input from '@/components/ui/Input.vue'
import { ApiError, createVendedor, updateVendedor, type Vendedor } from '@/lib/api'

const props = defineProps<{
  vendedor: Vendedor | null
}>()

const emit = defineEmits<{
  saved: []
  cancel: []
}>()

const nome = ref(props.vendedor?.nome ?? '')
const isSubmitting = ref(false)
const error = ref<string | null>(null)
const fieldErrors = ref<Record<string, string[]>>({})

async function handleSubmit() {
  error.value = null
  fieldErrors.value = {}
  isSubmitting.value = true

  try {
    if (props.vendedor) {
      await updateVendedor(props.vendedor.id, { nome: nome.value })
    } else {
      await createVendedor({ nome: nome.value })
    }
    emit('saved')
  } catch (err) {
    if (err instanceof ApiError) {
      error.value = err.message
      fieldErrors.value = err.errors ?? {}
    } else {
      error.value = 'Não foi possível conectar à API.'
    }
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>{{ vendedor ? `Editar vendedor: ${vendedor.nome}` : 'Cadastrar vendedor' }}</CardTitle>
      <CardDescription v-if="vendedor">ID: {{ vendedor.id }}</CardDescription>
    </CardHeader>
    <form @submit.prevent="handleSubmit">
      <CardContent class="flex flex-col gap-1">
        <label for="nome" class="text-sm font-medium">Nome</label>
        <Input id="nome" v-model="nome" required />
        <p v-for="msg in fieldErrors.nome" :key="msg" class="text-xs text-destructive">{{ msg }}</p>
        <p v-if="error" class="text-sm text-destructive">{{ error }}</p>
      </CardContent>
      <CardFooter class="gap-2">
        <Button type="submit" :disabled="isSubmitting">
          {{ isSubmitting ? 'Salvando...' : vendedor ? 'Salvar alterações' : 'Cadastrar' }}
        </Button>
        <Button type="button" variant="outline" @click="emit('cancel')">Cancelar</Button>
      </CardFooter>
    </form>
  </Card>
</template>

// frontend-react/src/pages/VendedorForm.tsx
import { useState, type FormEvent } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { ApiError, createVendedor, updateVendedor, type Vendedor } from '@/lib/api'

export function VendedorForm({
  vendedor,
  onSaved,
  onCancel,
}: {
  vendedor: Vendedor | null
  onSaved: () => void
  onCancel?: () => void
}) {
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [fieldErrors, setFieldErrors] = useState<Record<string, string[]>>({})

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError(null)
    setFieldErrors({})
    setIsSubmitting(true)

    const formData = new FormData(event.currentTarget)
    const data = { nome: String(formData.get('nome') ?? '') }

    try {
      if (vendedor) {
        await updateVendedor(vendedor.id, data)
      } else {
        await createVendedor(data)
      }
      onSaved()
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message)
        setFieldErrors(err.errors ?? {})
      } else {
        setError('Não foi possível conectar à API.')
      }
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>{vendedor ? `Editar vendedor: ${vendedor.nome}` : 'Cadastrar vendedor'}</CardTitle>
        {vendedor && <CardDescription>ID: {vendedor.id}</CardDescription>}
      </CardHeader>
      <form onSubmit={handleSubmit}>
        <CardContent className="flex flex-col gap-1">
          <label htmlFor="nome" className="text-sm font-medium">
            Nome
          </label>
          <Input id="nome" name="nome" required defaultValue={vendedor?.nome} />
          {fieldErrors.nome?.map((msg) => (
            <p key={msg} className="text-xs text-destructive">
              {msg}
            </p>
          ))}
          {error && <p className="text-sm text-destructive">{error}</p>}
        </CardContent>
        <CardFooter className="gap-2">
          <Button type="submit" disabled={isSubmitting}>
            {isSubmitting ? 'Salvando...' : vendedor ? 'Salvar alterações' : 'Cadastrar'}
          </Button>
          {onCancel && (
            <Button type="button" variant="outline" onClick={onCancel}>
              Cancelar
            </Button>
          )}
        </CardFooter>
      </form>
    </Card>
  )
}
